// Code generated by ipod static plugins import generator. DO NOT EDIT.

package plugins

import (
	"github.com/oandrew/ipod/plugins/ipod_defaults"
)

func init() {
	registerPlugin(&ipod_defaults.IpodPlugin)
}
