// +build ignore

package main

import (
	"fmt"
	"io/fs"
	"io/ioutil"
	"os"
	"text/template"
)

func filterPluginDirs(fileInfos []fs.FileInfo) []fs.FileInfo {
	pluginDirs := make([]fs.FileInfo, 0)
	for _, fileInfo := range fileInfos {
		if fileInfo.IsDir() && fileInfo.Name() != "internal" {
			pluginDirs = append(pluginDirs, fileInfo)
		}
	}
	return pluginDirs
}

func main() {
	pluginsPackageFiles, err := ioutil.ReadDir(".")
	if err != nil {
		fmt.Fprintln(os.Stderr, "Unable to read contents of plugins package directory.")
		os.Exit(1)
	}

	templateFuncMap := template.FuncMap{
		"filter": filterPluginDirs,
	}
	importsFileTemplate := template.Must(
		template.New("staticPluginImports").Funcs(
			templateFuncMap,
		).Parse(`// Code generated by ipod static plugins import generator. DO NOT EDIT.

package plugins

import (
{{range . | filter}}	"github.com/oandrew/ipod/plugins/{{.Name}}"{{end}}
)

func init() {
{{range . | filter}}	registerPlugin(&{{.Name}}.IpodPlugin){{end}}
}
`,
		),
	)

	outFile, err := os.Create("static_plugin_imports.go")
	if err != nil {
		fmt.Fprintln(os.Stderr, "Unable to create the generated code file: static_plugin_imports.go.")
		os.Exit(1)
	}

	err = importsFileTemplate.Execute(outFile, pluginsPackageFiles)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error generating import for static plugins.")
		fmt.Fprintln(os.Stderr, "This is usually caused by an invalid plugin. See error detials below:")
		fmt.Fprintln(os.Stderr, err.Error())
	}
}
